global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'k8s-ops'
    static_configs:
      - targets: ['localhost:8000']
        labels:
          service: 'k8s-ops-metrics'
